### ISSUE TITLE
Rectangle mpl selector CI failure

### ISSUE THREAD

**Issue by larrybradley** [astropy/regions#422]
The `TestRectanglePixelRegion.test_mpl_selector_drag` CI test started failing last night (after I merged https://github.com/astropy/regions/pull/392), but it fails *only* on macos python 3.9 (`py39-test-alldeps`).  I cannot reproduce this failure locally -- all tests pass when running this tox test on my mac.

There is a ` KeyError: 'draw_event'` being raised from `matplotlib`, see
https://github.com/astropy/regions/runs/5054472167?check_suite_focus=true.

CC: @dhomeier

**Comment by dhomeier** [comment]
I can reproduce it with 3.5.1, only in my case it always fails on the `'key_release_event'` signal instead of
```python
self._func_cid_map.setdefault(signal, {})
(https://github.com/astropy/regions/runs/5054472167?check_suite_focus=true#step:6:222)
        proxy = _weak_or_strong_ref(func, self._remove_proxy)
(https://github.com/astropy/regions/runs/5054472167?check_suite_focus=true#step:6:223)
>       if proxy in self._func_cid_map[signal]:
(https://github.com/astropy/regions/runs/5054472167?check_suite_focus=true#step:6:224)
E       KeyError: 'draw_event'
(https://github.com/astropy/regions/runs/5054472167?check_suite_focus=true#step:6:225)
```
Looks like the signal is removed right again  after `setdefault` (erratically?) in `self._remove_proxy`; the test also only fails when I am running at least the full `TestRectanglePixelRegion`, not just the `mpl_selector` ones – and obviously the virtually identical `TestEllipsePixelRegion` passes without problems.
It's also passing again with the current HEAD `3.6.0.dev1530`, but I cannot fathom what changes might have fixed it.

**Comment by larrybradley** [comment]
New data point:  in the cron CI run last night, the macos py39-alldeps test **passed**, but the windows py39-alldeps test failed (https://github.com/astropy/regions/runs/5088806452?check_suite_focus=true).  Another heisenbug?

**Comment by larrybradley** [comment]
Interestingly, the CI tests have all been passing since I merged #424, even though that seems completely unrelated.

**Comment by larrybradley** [comment]
Closing this now since the CI has been passing -- will reopen if it reappears.

**Comment by larrybradley** [comment]
The CI failure is back: https://github.com/astropy/regions/runs/5227025176?check_suite_focus=true#step:6:230

**Comment by larrybradley** [comment]
Haven't seen this error in almost 2 years, so closing.
