### ISSUE TITLE
Angle consistency with regions in different coordinate systems

### ISSUE THREAD

**Issue by LauraOlivera** [astropy/regions#428]
Hello. I have encountered a strange behavior when saving regions to file and opening them again.
Using:
- astropy == 4.3.1
- regions == 0.5
- python == 3.7

I create an elliptical region with a given angle in Galactic coordinates. Then save it to file, but when I open it again, the central coordinate has been transformed to ra-dec coordinates, while the angle has been left unchanged. Which effectively changes the orientation of the region because of the rotation between the two coordinate frames.
```
from regions import EllipseSkyRegion, Regions
import astropy.units as u

test = EllipseSkyRegion(center = SkyCoord(l = 0, b = 0, unit='deg', frame='galactic'),
                         width=0.3*u.deg,
                         height = 0.65*u.deg,
                         angle=-18*u.deg)

test.write('test.reg')

test_again = Regions.read('test.reg')[0]
print(test_again)
```
results in 
```
>> Region: EllipseSkyRegion
center: <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg
    (266.404996, -28.936172)>
width: 0.3 deg
height: 0.65 deg
angle: -18.0 deg
```

Visually, plotting `test` results in 
![image](https://user-images.githubusercontent.com/22521727/154039809-b28b4bd1-00cf-4ed9-8870-2614ab265a9d.png)
whereas plotting `test_again`, that is, the region after reading it results in
![image](https://user-images.githubusercontent.com/22521727/154039879-21477f02-683e-4d2a-9e39-1e6a4d3e5c8d.png)

This feels like a bug but maybe it is me doing something silly? I would appreciate help if so. Thanks a lot!

**Comment by keflavich** [comment]
I'd definitely consider this a bug.  First off, `.write` shouldn't change coordinate systems by default - so that's an error in the ds9 writer that may be prevalent everywhere.  Second, it does appear that the angle isn't changed when the coordinate is.

Our testing should catch this, so this highlights a hole in the testing framework.  We apparently don't have round-trip tests involving:

(1) region files containing regions specified in different coordinate systems (this is allowed by ds9, at least)
(2) regions with angles being converted from fk5->galactic->fk5 (for example)

I don't know if this has always been present, but it could have been introduced in the generalized io framework rewrite.

**Comment by larrybradley** [comment]
This bug has always been there.  I'm in the process of rewriting the `ds9` reader and writer to fix this bug (and many others).  Hopefully will have a PR by the end of the week.
