### ISSUE TITLE
Desire for a .to_table() method

### ISSUE THREAD

**Issue by janerigby** [astropy/regions#439]
I'm surprised that the regions doesn't have a method to generate an astropy table.  I wanted to turn a set of regions (in this case, stars to be photometered) into a table, hack the table and from that generate a new set of regions.  Shouldn't there be a Regions.to_table() method?

**Comment by keflavich** [comment]
Regions don't lend themselves to easy serialization in table form, since they can be very heterogeneous.  If the regions are all of the same variety (circles, say), then it makes sense to put them into a table - but in that case, they can be treated as photutils apertures.  Polygons and other more complex regions can have very long definitions.

So, what sort of use case are you envisioning here?  You have a bunch of point regions that you want to convert to a table of coordinates?  Or do you have any sorts of shapes associated with the stars?

**Comment by janerigby** [comment]
Catching up on multiple Qs.  Yes, I created the regions in ds9.  In this case, the shapes are circles.  And yes, I wanted to dump the (x,y) coordinates from the regions to a table, so that I could do math on the table (filter by position, for example).  In this case, I'm thinking about "a regions file" as a homogenous collection of regions. I totally see your point @keflavich that Regions are set up to be more general than that, which is why my question isn't resonating.  

The 3 lines that @larrybradley wrote are perfect, and if a typical user could figure them out from the documentation, then I totally agree, there's no need for a .to_table() method.  I know the documentation is in work now-- from the v0.5 documentation, I would have never figure out those 3 steps. I don't see `region.center.xy `listed anywhere -- that's clearly the magic step.  Where would a user find that?

**Comment by larrybradley** [comment]
@janerigby  `region.center.xy` is shorthand for two separate things.  The first, `region.center`, simply returns the center of the `CirclePixelRegion` (documented here: https://astropy-regions.readthedocs.io/en/stable/api/regions.CirclePixelRegion.html#regions.CirclePixelRegion.center).  It returns a `PixCoord` object (https://astropy-regions.readthedocs.io/en/stable/api/regions.PixCoord.html#regions.PixCoord), but in my example I wanted to  get the `(x, y)` values as a tuple instead of a `PixCoord`.  To do that there is a `PixCoord.xy` attribute (documented here: https://astropy-regions.readthedocs.io/en/stable/api/regions.PixCoord.html#regions.PixCoord.xy).  There are also examples of this on the "Getting Started" page under the "Coordinates" section (https://astropy-regions.readthedocs.io/en/stable/getting_started.html#coordinates).

 Documentation can always be improved, but we try our best!
