### ISSUE TITLE
Return a Mask class from the to_mask() method

### ISSUE THREAD

**Issue by larrybradley** [astropy/regions#55]
Just to follow-up on https://github.com/astropy/regions/issues/30, it would be better if the `to_mask()` method returns a `Mask` object.  The `Mask` object would be initialized with the mask array and the tuple slice and it could then handle the cases where the aperture is partially (or completely) outside of the image.

**Comment by cdeil** [comment]
@larrybradley - Would you advocate starting a `Mask` class from scratch in `regions`? Or is there some class in `astropy` or other affiliated  packages that could be the starting point?

FYI: in Gammapy, we have been developing a [SkyMap](https://gammapy.readthedocs.io/en/latest/api/gammapy.image.SkyMap.html) class (will get renamed to `SkyImage` tomorrow). It has cut and paste via your Cutout class, but doesn't store offset as data member. I plan to integrate it with regions soon, but have no plan to propose it for Astropy core. We've discussed the possibility of adding an image class to Astropy several times, I think the conclusion was always that it's not welcome? Or maybe it was just that no-one made a PR?

I'm always +1 for more object-oriented API, grouping things like data and offset and making it convenient to interact with other objects like regions via methods instead of many standalone functions.

So @larrybradley - Could you elaborate a little what exactly you propose be added here, maybe put some pseudo-code what this `Mask` is supposed to do for the most common use cases?

**Comment by larrybradley** [comment]
The `Mask` class was actually @astrofrog's idea and came out of a discussion I had with him earlier today (he was visiting STScI).  It would be a new class within `regions` (but it would likely reuse some code from `Cutout2D`).

The `to_mask()` method currently returns a mask array and tuple slice, but the region objects know nothing about the data on which the mask will be applied (e.g. performing photometry).  If the region falls partially or completely off the image, then the returned `tuple slice` will be incorrect.  Each and every time the mask is applied to data, the boundary conditions would need to be checked.  By returning a `Mask` object, the `Mask` object could then handle the boundary conditions (centralizing such code in a single place).  Perhaps something like

```
from regions import CirclePixelRegion
region = CirclePixelRegion(...)
mask = region.to_mask()     # returns a mask object
data_subset = mask.apply(data)
```
where the `apply()` method would handle the boundary checking.

Currently you would need to do:

```
from regions import CirclePixelRegion
region = CirclePixelRegion(...)
mask, slice_x, slice_y = region.to_mask()

# need code here to check slice boundary conditions

data_subset = mask * data[slice_y, slice_x]
```

**Comment by cdeil** [comment]
👍

**Comment by astrofrog** [comment]
Done in #71
