### ISSUE TITLE
Polygon region vertices

### ISSUE THREAD

**Issue by larrybradley** [astropy/regions#57]
The `PolygonPixelRegion` is initialized with a `vertices` input, which it appears are _absolute_ positions.  That makes it a bit more difficult to move the region to different positions.  Instead, should the `vertices` define a shape relative to `(0, 0)` and then have an additional `position` (or `center`?) parameter that defines the absolute position (i.e. a shift from `(0, 0)`)?

**Comment by cdeil** [comment]
I don't care either way. Having absolute as data members has the advantage that no additional center is needed. The non-public region package I have been using so far even had a rotation point and rotation angle as data member for every region, because rotations were a common operation. I'm not advocating for this here.

My suggestion: whoever volunteers to implement polygons gets to choose. :-)

How does `shapely` and `sphere` do this? Do they have extra data members for such a shift on the polygon objects?

**Comment by astrofrog** [comment]
If we do include this, I would suggest calling it ``offset`` (center would be misleading and position might be confusing since there are multiple positions).

**Comment by cdeil** [comment]
I'm moving the milestone to 0.3.
But if someone has time to work on polygons within the next ~week, it could still go in the 0.2 release.

@larrybradley - Could you please comment again what you think should be done for polygons, based on the discussion here? How about copying over the pixel polygon code from Ginga  (see links in #69)?

**Comment by larrybradley** [comment]
@cdeil My motivation to define the polygon using *relative* positions (e.g. from zero) instead of *absolute* positions was for aperture photometry.  In other words, the *shape* of the polygon can be defined by the *relative* positions.  That would be like a `PolygonAperture` object.  The `PolygonAperture` object could then be applied to the data at different absolute positions.

If the region is defined using *absolute* vertices, I would need to redefine a new `PolygonAperture` for every new position it is to be applied to the data.

**Comment by larrybradley** [comment]
BTW, if the polygon is defined with *relative* positions, we would need to add an additional `position` (`origin`?) keyword for the absolute position.

**Comment by larrybradley** [comment]
@cdeil  It looks like `ginga` is using *absolute*-position vertices since the region is defined by drawing on a canvas.

**Comment by cdeil** [comment]
Moved to 0.4 milestone.

**Comment by cdeil** [comment]
See comment by @larrybradley in https://github.com/astropy/regions/pull/281#issuecomment-502838913

That PR is closed, let's continue the discussion here and try to find a solution.

---

I can see how this symmetry to the other regions into location and shape is nice for `PixelPolygon`, and also I agree 100% that having regions and photutils as similar as possible is important.

I see two major issues with adding this property:
- not supported by our current serialisation formats, especially DS9? Or is it?
- separation into position and shape doesn't work for `SkyPolygon`? Or does it?

The other argument  you give is "no need to recompute polygon vertices for new position".
Does this really matter? Would the time / memory to copy the vertices Numpy array ever matter in your analyses? For us in Gammapy, we would probably have 3 - 100 vertices and maybe 1000 regions max, and the time and memory for vertices copies would never be important compared to the analyses we do using these regions.

**Comment by larrybradley** [comment]
I plan to eventually have the `photutils` aperture classes wrap around the region classes (after they are stable and merged into astropy core - something that would great for astropy 4.0).  One big difference is that aperture classes can be defined with an array of (x, y) positions (which will change to vector `PixCoord` in photutils apertures 2.0), but I plan the rest of the parameters will have the same names as region parameters -- making photutils and regions very similar.  

I'm not sure about the serialization formats (but if so could an adapter be used before initialization?).

I think `SkyPolygon` could work just like the other "sky" regions, which simply convert the center SkyCoord to pixel, and use a pixel scale to convert the shape parameters (e.g. radius) from angular to pixel units.

I haven't really thought about time/memory.  My concern was more from a public API and user experience.  A typical use case for photutils aperture is define a single aperture shape at a few thousand positions -- all within a *single* object, e.g.:

```python
aper1 = CircularAperture(x, y, r=3.)  # where len(x) = len(y) = ~1-2k
aper2 = CircularAperture(x, y, r=5.)
aper3 = PolygonAperture(x, y, vertices)  # vertices defined relatively

tbl = aperture_photometry(data, (aper1, aper2, aper3))
```
The output table has a row for each (x, y) position (e.g. a single source) and separate columns for the photometry in each of the input apertures.  I don't know how this current API would allow for polygon apertures defined only with absolute `vertices`.

In that case the user would need to compute the absolute `vertices` for each of their input positions, do the photometry *separately* for each source position, and then collect all the results in an array, and then add a column(s) to the table.  That's not a very friendly user experience.

Perhaps we could also define a `RegularPolygonPixelRegion` in regions defined by two parameters: `center` (true center) and `num_sides`?

**Comment by cdeil** [comment]
@larrybradley - Thanks for explaining!

So we'd support array positions, but shape parameters like `radius`, `width`, `height`, `angle`, polygon vertices couldn't be arrays also? Isn't this mixed solution ultimately still too limiting, and many users would need to have a list of `Region` objects? See e.g. http://cxc.harvard.edu/ciao/threads/masks/ for an example from Chandra, where the PSF in the image center is much better than at the edge.

We could go towards a package that supports arrays of shapes in a single `Region` object as much as possible, but it does add work and complexity (e.g. to make sure all operations broadcast, and to have if / else whether it's scalar or array and added for loops e.g. in plotting, and in I/O routines), so we should be sure it's really worth it.

---

Concerning `center`, how would the `__init__` and data members in https://astropy-regions.readthedocs.io/en/latest/api/regions.PolygonSkyRegion.html change? How do you define and store the vertices if you have no WCS? Do you rotate the sky to have `(lon, lat) = (0, 0)` at the center and store angles in that frame?

Also note https://spacetelescope.github.io/spherical_geometry/spherical_geometry/user.html - I think the idea to add an `inside` point data member with a good default is great, no?

How does DS9 (or Aladin / Ginga / ...) display large polygons e.g. on all-sky images? Probably they transform the vertices to pixel coordinates, irrespective of the WCS of the image? So it is fundamentally different than what they do for regions that have a center?

I'll try to look into polygons and what the common astro visualisation tools do some more soon, but if anyone knows - please comment here!

**Comment by cdeil** [comment]
I added pixel polygon area method in #293 because it's an example that can inform the discussion on vertex representation a bit. To get a good precision result, one has to use offset coordinates, and also to avoid code duplication, having a closed polygon representation where the first and last point are the same would be advantageous.

In [spherical_geometry](https://spacetelescope.github.io/spherical_geometry/spherical_geometry/user.html#representation) the user is required to input a closed polygon, in [matplotlib](https://github.com/matplotlib/matplotlib/blob/fdcdf4fac9e00d0256faad9478d4a0aeba1e88d5/lib/matplotlib/patches.py#L1017-L1039) an option is provided to pass in closed polygon or not, always go to closed polygon on init doing an array copy.

So to which internal and public API representation of polygon vertices (and possibly center, interior point) should we go?

For us in Gammapy, efficiency is never a concern, so doing an array copy on init and going to an internal representation that is closed (and xyz for sky polygon like how spherical_geometry does it) seems like a good idea (and to to `[:-1]` as needed, e.g. in DS9 I/O). But really anything you prefer should be OK, we just need to decide to be able to move ahead with this.
