### ISSUE TITLE
Put docs on readthedocs

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#9]
To include in the frontpage:

 * [ ] a timeline for inclusion in astropy core (>=3 months, but the goal is to have it in core)
 * [ ] correctness comparison to pyregion
 * [ ] speed comparison to pyregion

**Comment by keflavich** [comment]
@joleroi you should be able to start the readthedocs package from this URL:
https://readthedocs.org/dashboard/import/?
though... I'm not seeing it there...

**Comment by joleroi** [comment]
I put a minimal docs page on rtd.

http://astropy-regions.readthedocs.org/en/latest/

**Comment by cdeil** [comment]
@keflavich - I'm closing this issue, since the title says "put docs on readthedocs" and they are up.

Concerning the other tasks you list above:
- I don't think we can give a timeline for inclusion in the astropy core ... we don't know when someone will work on this and when it will be ready.
- Concerning comparison to pyregion, I'll make a separate issue.
